#!/bin/sh

if [ "$#" -lt 1 ]; then
  exit 1
fi

create_directory() {
  DIR="./lua/advent-of-code/$YEAR/$DAY"

  if [[ -d "$DIR/" ]]; then
    echo "$DIR already exists. exiting"
  else
    mkdir -p $DIR
    aoc d -i "$DIR/input.txt" -p "$DIR/puzzle.md" -y $YEAR -d $DAY > /dev/null 2>&1
    touch "$DIR/test.txt"
    cat > "$DIR/init.lua" << EOM
local AOC = require "advent-of-code.AOC"
AOC.reload()

---@class AOCDay$YEAR$DAY: AOCDay
---@field input string[]
local M = AOC.create("$YEAR", "$DAY")

function M:parse_input(file)
  self.__super.parse_input(self, file)
end

function M:solve1()
  self.solution:add("1", nil)
end

function M:solve2()
  self.solution:add("2", nil)
end

M:run()

return M
EOM
  fi
}

case "$1" in
  r)
    if [ "$#" -lt 3 ]; then
      exit 1
    fi
    test=0
    if [ "$#" -eq 4 ]; then
      test=$4
    fi
    pushd ./lua
    luajit advent-of-code/$2/$(printf %02d $3)/init.lua $test
    popd
    ;;
  s)
    if [ "$#" -lt 5 ]; then
      exit 1
    fi
    aoc s -y $2 -d $3 $4 $5
    ;;
  d)
    if [ "$#" -lt 3 ]; then
      exit 1
    fi
    aoc d -y $2 -d $3 -P -p lua/advent-of-code/$2/$(printf %02d $3)/puzzle.md -o
    ;;
  l)
    if [ "$#" -lt 2 ]; then
      exit 1
    fi
    for DAY in $(seq -f %02g 25);
    do
      echo $2:$DAY
      YEAR=$2 create_directory
    done
    ;;
  n)
    YEAR=$2 DAY=$(printf %02d $3) create_directory
    ;;
esac
