#!/bin/sh

CURRENT_YEAR=$(date +"%Y")
CURRENT_DAY=$(date +"%d")

usage() {
  echo "$0 usage:"
  echo "    -y  use default year ($CURRENT_YEAR) and day ($CURRENT_DAY)"
  echo "    -D  specify year and date as XXXX:XX, e.g. 2023:05"
  echo "    -h  show this help"
}

create_directory() {
  DIR="./lua/advent-of-code/$YEAR/$DAY"

  if [[ -d "$DIR/" ]];
  then
    echo "$DIR already exists. exiting"
    exit 1
  fi

  mkdir -p $DIR
  aoc d -i "$DIR/input.txt" -p "$DIR/puzzle.md" -y $YEAR -d $DAY > /dev/null 2>&1
  touch "$DIR/test.txt"
  cat > "$DIR/init.lua" << EOM
local AOC = require "advent-of-code.AOC"
AOC.reload()

local M = AOC.create("$YEAR", "$DAY")

function M:parse_input(file)
  self.__super.parse_input(self, file)
end

function M:solve1()
  self.solution:add("1", nil)
end

function M:solve2()
  self.solution:add("2", nil)
end

M:run(true)

return M
EOM
}

open_url() {
  xdg-open "https://adventofcode.com/$YEAR/day/$(($DAY + 0))" &
}

if [[ $# -eq 0 ]];
then
  usage
  exit 0
fi

while getopts ":hycY:D:u" arg; do
  case $arg in
    y)
      YEAR=$CURRENT_YEAR
      DAY=$CURRENT_DAY
      create_directory
      ;;
    D)
      DATE=(${OPTARG//:/ })
      YEAR=${DATE[0]}
      DAY=${DATE[1]}
      if [[ ${#YEAR} -ne 4 ]];
      then
        echo "wrong year format"
        exit 1
      fi
      if [[ ${#DAY} -ne 2 ]];
      then
        echo "wrong day format"
        exit 1
      fi
      create_directory
      ;;
    c)
      YEAR=$CURRENT_YEAR
      DAY=$CURRENT_DAY
      git add "lua/advent-of-code/$YEAR/$DAY"
      git commit -m "📅 $YEAR/$DAY: add solution"
      ;;
    u)
      open_url
      ;;
    h)
      usage
      exit 0
      ;;
  esac
done
