#!/bin/sh

CURRENT_YEAR=$(date +"%Y")
CURRENT_DAY=$(date +"%d")

usage() {
  echo "$0 usage:"
  echo "    -y  use default year ($CURRENT_YEAR) and day ($CURRENT_DAY)"
  echo "    -D  specify year and date as XXXX:XX, e.g. 2023:05"
  echo "    -h  show this help"
}

if [[ $# -eq 0 ]];
then
  usage
  exit 0
fi

while getopts ":hyY:D:" arg; do
  case $arg in
    y)
      YEAR=$CURRENT_YEAR
      DAY=$CURRENT_DAY
      ;;
    D)
      DATE=(${OPTARG//:/ })
      YEAR=${DATE[0]}
      DAY=${DATE[1]}
      if [[ ${#YEAR} -ne 4 ]];
      then
        echo "wrong year format"
        exit 1
      fi
      if [[ ${#DAY} -ne 2 ]];
      then
        echo "wrong day format"
        exit 1
      fi
      ;;
    h)
      usage
      exit 0
      ;;
  esac
done

DIR="./lua/advent-of-code/$YEAR/$DAY"

if [[ -d "$DIR/" ]];
then
  echo "$DIR already exists. exiting"
  exit 1
fi

mkdir -p $DIR
touch "$DIR/input.txt"
touch "$DIR/test.txt"
cat > "$DIR/init.lua" << EOM
local AOCDay = require "advent-of-code.AOCDay"

local M = AOCDay:new("$YEAR", "$DAY")

return M
EOM
