#!/bin/sh

YEAR=$1
DAY=$2

if [[ $# -ne 2 ]];
then
  echo "too few arguments"
  echo "usage: ./new_day 2022 03"
  exit 1
fi

FILE_PATH="./lua/advent-of-code/$YEAR/$DAY"

if [[ -d "$FILE_PATH/" ]];
then
  echo "$FILE_PATH already exists"
  exit 1
fi

mkdir -p $FILE_PATH
touch "$FILE_PATH/input.txt"
touch "$FILE_PATH/test.txt"

cat > "$FILE_PATH/init.lua" << EOM
local AOCDay = require "advent-of-code.AOCDay"

local M = AOCDay("$YEAR", "$DAY")

return M
EOM
